logger:
  mode: rotate
  level: error
  single:
    path: /tmp/ifman.log
    perm: 0644
  rotate:
    dir: /tmp/ifman
    age: 1296000
    cut_period: 86400

interface:

route:

verify:
  check_period: 60
